# .goreleaser.yml
# Build customization
project_name: ircdog
builds:
  - main: ircdog.go
    env:
      - CGO_ENABLED=0
    binary: ircdog
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    replacements:
      amd64: x86_64
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
